# Site settings
title: Louisianime
email: admin@louisianime.com
description: "Louisianime convention."
baseurl: ""
url: "http://www.louisianime.com/"
twitter_username: louisianime



# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
encoding: utf-8

#paginate_path: "news/page:num"
