# Site settings
title: Louisianime
email: your-email@domain.com
description: "Louisianime convention."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

#paginate_path: "news/page:num"
